services:
#    user.example:
#        class: UserBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    redirect.after.login:
        class:  UserBundle\Redirection\LoginAfterRedirection
        arguments: ["@router"]